# Generated by Django 4.1.5 on 2023-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='about/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
